# Generated by Django 4.0.1 on 2022-09-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
    ]
